### ISSUE TITLE
Running on synology

### ISSUE THREAD

**Issue by ghost** [dskaggs/docker-organize#7]
Hi,
I’m trying to run your organize docker container on synology nas but when I start the container it directly crashes. 
I don’t know why and nothing appears in the log
I’m new with using docker so maybe I done something wrong ... 
I searched a lot for documentation but I didn’t find something helpful. 
Could you help me ?
Thanks a lot !
François

**Comment by dskaggs** [comment]
@Francoisb24 Apologies for that. Your error was likely due to the fact that the `/var/log/organize` directory didn't exist. I've updated the examples in the README to show how to map this to a volume outside the container so that you can see the results of each execution.
